apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: resource-
spec:
  entrypoint: whalesay
  templates:
    - name: k8s-owner-reference
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            generateName: owned-eg-
          data:
            some: value
